[package]
name = "rust2go-macro"
version = "0.4.1"

description = "Rust2go macro."

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true


[lib]
proc-macro = true

[dependencies]
rust2go-common = { workspace = true }

proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
