[package]
name = "rust2go"
version = "0.4.3"

description = "Rust2go main shared library."

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rust2go-macro = { workspace = true }
rust2go-convert = { workspace = true }
rust2go-gen = { workspace = true, optional = true }

bindgen = { version = "0.72", optional = true }
fs-set-times = { version = "0.20", optional = true }

[features]
default = []
build = ["bindgen", "rust2go-gen", "fs-set-times"]
