[package]
name = "rust2go-cli"
version = "0.4.2"

description = "Rust2go commandline tool."

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rust2go-gen = { version = "0.1.0", path = "../rust2go-gen" }

clap = { version = "4", features = ["derive"] }

[[bin]]
name = "rust2go-cli"
path = "src/main.rs"
